---
# tasks file for deploy_user

- name: create a deploy user
  user: name={{ deploy_user_name}}
    shell=/bin/bash
    groups={{deploy_groups}}

- name: add public key for current user
  authorized_key: user={{ deploy_user_name}}
    key: {{deploy_user_ssh_priv_key_path}}
