---
# tasks file for deploy_user

- name: create our deploy groups
  group: >
    name={{ item }}
    state=present
  with_items: deploy_groups

- name: create a deploy user
  user: >
    name={{ deploy_user_name }}
    shell=/bin/bash
    groups={{ deploy_groups }}.join(',')

- name: add ssh directory for deploy user
  file: >
    path=/home/{{ app }}/.ssh
    owner={{  deploy_user_name }}
    state=directory
    mode=700

- name: add deploy key for deploy user
  copy: >
    src={{ deploy_user_ssh_priv_key_path }}
    dest=/home/{{ deploy_user_name }}/.ssh/deploy
    mode=600
